//! Mathematical Reasoning System
//!
//! Pattern-based conjecture generation and proof discovery:
//! - Identify patterns in successful proofs
//! - Generate new conjectures by analogy
//! - Find proof paths using Gabriel Cell graph structure
//! - Emergent mathematical intuition

use gabriel_core::{GabrielCell, InformationQuantum};
use std::sync::Arc;
use parking_lot::RwLock;
use serde::{Deserialize, Serialize};
use tracing::{debug, info};
use ahash::AHashMap;

/// Type of reasoning pattern
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ReasoningPattern {
    /// Direct implication: A → B
    DirectImplication,

    /// Transitivity: A → B, B → C ⟹ A → C
    Transitivity,

    /// Contradiction: ¬A leads to contradiction
    Contradiction,

    /// Induction: P(0) ∧ (P(n) → P(n+1)) ⟹ ∀n P(n)
    Induction,

    /// Analogy: A ≈ B, property(A) ⟹ maybe property(B)
    Analogy,

    /// Construction: Build object with desired properties
    Construction,

    /// Case analysis: Cover all cases
    CaseAnalysis,
}

/// A discovered reasoning pattern
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DiscoveredPattern {
    pub pattern_type: ReasoningPattern,
    /// Neuron path that exhibited this pattern
    pub neuron_path: Vec<u64>,
    /// How often this pattern succeeded
    pub success_count: usize,
    /// How often it failed
    pub failure_count: usize,
    /// Confidence in pattern (0.0-1.0)
    pub confidence: f64,
    /// When was it discovered?
    pub discovered_at: f64,
}

impl DiscoveredPattern {
    pub fn new(pattern_type: ReasoningPattern, path: Vec<u64>, time: f64) -> Self {
        Self {
            pattern_type,
            neuron_path: path,
            success_count: 0,
            failure_count: 0,
            confidence: 0.5,
            discovered_at: time,
        }
    }

    pub fn record_success(&mut self) {
        self.success_count += 1;
        self.update_confidence();
    }

    pub fn record_failure(&mut self) {
        self.failure_count += 1;
        self.update_confidence();
    }

    fn update_confidence(&mut self) {
        let total = self.success_count + self.failure_count;
        if total > 0 {
            self.confidence = self.success_count as f64 / total as f64;
        }
    }
}

/// Configuration for reasoning system
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReasoningConfig {
    /// Minimum confidence to use a pattern
    pub min_pattern_confidence: f64,

    /// Maximum depth for proof search
    pub max_search_depth: usize,

    /// Analogy threshold (minimum resonance)
    pub analogy_threshold: f64,

    /// Maximum patterns to track
    pub max_patterns: usize,
}

impl Default for ReasoningConfig {
    fn default() -> Self {
        Self {
            min_pattern_confidence: 0.6,
            max_search_depth: 10,
            analogy_threshold: 0.7,
            max_patterns: 1000,
        }
    }
}

/// Conjecture generated by the system
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Conjecture {
    pub id: u64,
    pub statement: String,
    /// Source pattern that inspired this
    pub source_pattern: ReasoningPattern,
    /// Confidence in conjecture
    pub confidence: f64,
    /// Supporting evidence (neuron IDs)
    pub evidence: Vec<u64>,
    pub created_at: f64,
}

impl Conjecture {
    pub fn new(
        id: u64,
        statement: String,
        pattern: ReasoningPattern,
        confidence: f64,
        time: f64,
    ) -> Self {
        Self {
            id,
            statement,
            source_pattern: pattern,
            confidence,
            evidence: Vec::new(),
            created_at: time,
        }
    }

    pub fn add_evidence(&mut self, neuron_id: u64) {
        self.evidence.push(neuron_id);
        // More evidence increases confidence (up to limit)
        self.confidence = (self.confidence * 0.9 + 0.1).min(0.95);
    }
}

/// Mathematical reasoning engine
pub struct MathematicalReasoning<Q: InformationQuantum> {
    gabriel_cell: Arc<GabrielCell<Q>>,
    config: ReasoningConfig,

    /// Discovered patterns
    patterns: Arc<RwLock<Vec<DiscoveredPattern>>>,

    /// Generated conjectures
    conjectures: Arc<RwLock<Vec<Conjecture>>>,

    /// Pattern usage statistics
    pattern_usage: Arc<RwLock<AHashMap<ReasoningPattern, usize>>>,

    current_time: Arc<RwLock<f64>>,
}

impl<Q: InformationQuantum> MathematicalReasoning<Q> {
    pub fn new(gabriel_cell: Arc<GabrielCell<Q>>, config: ReasoningConfig) -> Self {
        Self {
            gabriel_cell,
            config,
            patterns: Arc::new(RwLock::new(Vec::new())),
            conjectures: Arc::new(RwLock::new(Vec::new())),
            pattern_usage: Arc::new(RwLock::new(AHashMap::new())),
            current_time: Arc::new(RwLock::new(0.0)),
        }
    }

    /// Find proof path between two concepts
    pub fn find_proof_path(&self, from: u64, to: u64) -> Option<Vec<u64>> {
        let paths = self.gabriel_cell.find_emergent_paths(
            from,
            to,
            self.config.max_search_depth,
        );

        // Return strongest path
        paths.first().cloned()
    }

    /// Detect reasoning pattern in a successful proof
    pub fn detect_pattern(&self, proof_path: &[u64]) -> Option<ReasoningPattern> {
        if proof_path.len() < 2 {
            return None;
        }

        // Simple heuristics for pattern detection

        // Direct path (length 2) → Direct implication
        if proof_path.len() == 2 {
            return Some(ReasoningPattern::DirectImplication);
        }

        // Long chain → Transitivity
        if proof_path.len() >= 3 {
            // Check if it's a simple chain
            let mut is_chain = true;
            for window in proof_path.windows(2) {
                if !self.gabriel_cell.has_edge(window[0], window[1]) {
                    is_chain = false;
                    break;
                }
            }

            if is_chain {
                return Some(ReasoningPattern::Transitivity);
            }
        }

        // TODO: More sophisticated pattern detection
        // - Induction: look for recursive structure
        // - Contradiction: look for cycles back to contradiction neuron
        // - Case analysis: look for branching structure

        Some(ReasoningPattern::DirectImplication)
    }

    /// Record a successful proof and extract pattern
    pub fn learn_from_proof(&self, proof_path: &[u64]) {
        if let Some(pattern_type) = self.detect_pattern(proof_path) {
            let current_time = *self.current_time.read();

            let mut patterns = self.patterns.write();

            // Find existing pattern or create new
            if let Some(pattern) = patterns.iter_mut()
                .find(|p| p.pattern_type == pattern_type && p.neuron_path == proof_path)
            {
                pattern.record_success();
            } else {
                let mut new_pattern = DiscoveredPattern::new(
                    pattern_type,
                    proof_path.to_vec(),
                    current_time,
                );
                new_pattern.record_success();
                patterns.push(new_pattern);

                debug!("Discovered new {:?} pattern", pattern_type);
            }

            // Update usage stats
            let mut usage = self.pattern_usage.write();
            *usage.entry(pattern_type).or_insert(0) += 1;

            info!("Learned from proof using {:?} pattern", pattern_type);
        }
    }

    /// Generate conjecture by analogy
    pub fn generate_by_analogy(&self, source: u64, target: u64) -> Option<Conjecture> {
        // Get source and target quanta
        let source_neuron = self.gabriel_cell.get_neuron(source)?;
        let target_neuron = self.gabriel_cell.get_neuron(target)?;

        let source_quantum = source_neuron.read().quantum.clone();
        let target_quantum = target_neuron.read().quantum.clone();

        // Check if analogous (high resonance)
        let resonance = source_quantum.resonance(&target_quantum);

        if resonance < self.config.analogy_threshold {
            return None;
        }

        // Generate conjecture
        let current_time = *self.current_time.read();
        let id = rand::random::<u64>();

        let statement = format!(
            "If property holds for {}, it may hold for {} (resonance: {:.2})",
            source, target, resonance
        );

        let mut conjecture = Conjecture::new(
            id,
            statement,
            ReasoningPattern::Analogy,
            resonance,
            current_time,
        );

        conjecture.add_evidence(source);
        conjecture.add_evidence(target);

        debug!("Generated conjecture by analogy: {}", conjecture.statement);

        Some(conjecture)
    }

    /// Generate conjectures based on discovered patterns
    pub fn generate_conjectures(&self, max_count: usize) -> Vec<Conjecture> {
        let patterns = self.patterns.read();
        let stats = self.gabriel_cell.stats();

        if stats.neuron_count < 2 {
            return Vec::new();
        }

        let mut generated = Vec::new();

        // Use high-confidence patterns to generate conjectures
        for pattern in patterns.iter().filter(|p| p.confidence > self.config.min_pattern_confidence) {
            if generated.len() >= max_count {
                break;
            }

            // Try to apply pattern to new neuron pairs
            let n1 = rand::random::<u64>() % stats.neuron_count as u64;
            let n2 = rand::random::<u64>() % stats.neuron_count as u64;

            if n1 != n2 {
                if let Some(conjecture) = self.generate_by_analogy(n1, n2) {
                    generated.push(conjecture);
                }
            }
        }

        let mut conjectures = self.conjectures.write();
        conjectures.extend(generated.clone());

        info!("Generated {} conjectures", generated.len());

        generated
    }

    /// Apply a reasoning pattern to generate new proof
    pub fn apply_pattern(
        &self,
        pattern: ReasoningPattern,
        start: u64,
        goal: u64,
    ) -> Option<Vec<u64>> {
        match pattern {
            ReasoningPattern::DirectImplication => {
                // Try direct connection
                if self.gabriel_cell.has_edge(start, goal) {
                    Some(vec![start, goal])
                } else {
                    None
                }
            }

            ReasoningPattern::Transitivity => {
                // Find intermediate path
                self.find_proof_path(start, goal)
            }

            _ => {
                // TODO: Implement other pattern applications
                None
            }
        }
    }

    /// Get most successful patterns
    pub fn top_patterns(&self, count: usize) -> Vec<DiscoveredPattern> {
        let mut patterns = self.patterns.read().clone();
        patterns.sort_by(|a, b| {
            b.confidence.partial_cmp(&a.confidence).unwrap_or(std::cmp::Ordering::Equal)
        });

        patterns.into_iter().take(count).collect()
    }

    /// Get all conjectures
    pub fn conjectures(&self) -> Vec<Conjecture> {
        self.conjectures.read().clone()
    }

    /// Tick time
    pub fn tick(&self, dt: f64) {
        let mut time = self.current_time.write();
        *time += dt;
    }

    /// Get pattern usage statistics
    pub fn pattern_stats(&self) -> AHashMap<ReasoningPattern, usize> {
        self.pattern_usage.read().clone()
    }

    /// Clear all patterns and conjectures (for experiments)
    pub fn reset(&self) {
        self.patterns.write().clear();
        self.conjectures.write().clear();
        self.pattern_usage.write().clear();
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use gabriel_core::GabrielCell;

    #[derive(Clone, Debug)]
    struct TestQuantum {
        id: u64,
        value: f64,
    }

    impl InformationQuantum for TestQuantum {
        type Id = u64;
        fn id(&self) -> u64 { self.id }
        fn resonance(&self, other: &Self) -> f64 {
            let diff = (self.value - other.value).abs();
            1.0 / (1.0 + diff)
        }
        fn energy(&self) -> f64 { self.value }
        fn fuse(&self, other: &Self, w: f64) -> Self {
            TestQuantum {
                id: self.id,
                value: self.value * (1.0 - w) + other.value * w,
            }
        }
    }

    #[test]
    fn test_pattern_detection() {
        let config = gabriel_core::GabrielConfig::default();
        let cell = Arc::new(GabrielCell::new(config));

        let n1 = cell.add_neuron(TestQuantum { id: 1, value: 1.0 }, [0.0; 4]);
        let n2 = cell.add_neuron(TestQuantum { id: 2, value: 2.0 }, [0.0; 4]);
        let n3 = cell.add_neuron(TestQuantum { id: 3, value: 3.0 }, [0.0; 4]);

        cell.connect(n1, n2, 0.8);
        cell.connect(n2, n3, 0.8);

        let reasoning = MathematicalReasoning::new(cell, ReasoningConfig::default());

        let pattern = reasoning.detect_pattern(&[n1, n2, n3]);
        assert_eq!(pattern, Some(ReasoningPattern::Transitivity));

        let pattern_direct = reasoning.detect_pattern(&[n1, n2]);
        assert_eq!(pattern_direct, Some(ReasoningPattern::DirectImplication));
    }

    #[test]
    fn test_learn_from_proof() {
        let config = gabriel_core::GabrielConfig::default();
        let cell = Arc::new(GabrielCell::new(config));

        let n1 = cell.add_neuron(TestQuantum { id: 1, value: 1.0 }, [0.0; 4]);
        let n2 = cell.add_neuron(TestQuantum { id: 2, value: 2.0 }, [0.0; 4]);

        cell.connect(n1, n2, 0.9);

        let reasoning = MathematicalReasoning::new(cell, ReasoningConfig::default());

        reasoning.learn_from_proof(&[n1, n2]);

        let patterns = reasoning.patterns.read();
        assert_eq!(patterns.len(), 1);
        assert_eq!(patterns[0].success_count, 1);
    }

    #[test]
    fn test_analogy_generation() {
        let config = gabriel_core::GabrielConfig::default();
        let cell = Arc::new(GabrielCell::new(config));

        let n1 = cell.add_neuron(TestQuantum { id: 1, value: 5.0 }, [0.0; 4]);
        let n2 = cell.add_neuron(TestQuantum { id: 2, value: 5.1 }, [0.0; 4]);

        let reasoning = MathematicalReasoning::new(cell, ReasoningConfig::default());

        // High resonance should generate conjecture
        let conjecture = reasoning.generate_by_analogy(n1, n2);
        assert!(conjecture.is_some());

        let conj = conjecture.unwrap();
        assert_eq!(conj.source_pattern, ReasoningPattern::Analogy);
        assert!(conj.confidence > 0.7);
    }

    #[test]
    fn test_proof_path_finding() {
        let config = gabriel_core::GabrielConfig::default();
        let cell = Arc::new(GabrielCell::new(config));

        let n1 = cell.add_neuron(TestQuantum { id: 1, value: 1.0 }, [0.0; 4]);
        let n2 = cell.add_neuron(TestQuantum { id: 2, value: 2.0 }, [0.0; 4]);
        let n3 = cell.add_neuron(TestQuantum { id: 3, value: 3.0 }, [0.0; 4]);

        cell.connect(n1, n2, 0.8);
        cell.connect(n2, n3, 0.8);

        let reasoning = MathematicalReasoning::new(cell, ReasoningConfig::default());

        let path = reasoning.find_proof_path(n1, n3);
        assert!(path.is_some());

        let p = path.unwrap();
        assert!(p.contains(&n1));
        assert!(p.contains(&n3));
    }
}
